In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch

In [3]:
torch.set_default_dtype(torch.float64)
# only floating type can be set as dytpe
# pytorch has 8 CPU type tensors, 8 GPU type tensors


In [4]:
torch.get_default_dtype()

torch.float64

In [5]:
tensor_arr= torch.Tensor(([1,2,3],[4,5,6]))
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
torch.is_tensor(tensor_arr)

True

In [7]:
torch.numel(tensor_arr)

6

In [8]:
tensor_uninitialised = torch.Tensor(2, 2)
# unitntialised, - give memmory but not instatiate
tensor_uninitialised 
# displays random values

tensor([[6.9011e-310, 6.9011e-310],
        [1.5810e-322, 3.1620e-322]])

In [9]:
tensor_initialised = torch.rand(2, 2)

In [10]:
tensor_initialised 
# quick to initalise params of wts of model

tensor([[0.5522, 0.3736],
        [0.7207, 0.7056]])

In [14]:
tensor_int = torch.Tensor([5,3]).type(torch.IntTensor)
# for making tensors on CPU, for GPU alternative use torch.cuda.IntTensor
tensor_int

tensor([5, 3], dtype=torch.int32)

In [15]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [16]:
tensor_float= torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float
# uses half memory of float32

tensor([1., 2., 3.], dtype=torch.float16)

In [17]:
tensor_fill = torch.full((2,6),fill_value=10)
tensor_fill

/pytorch/aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [ ]:
# torch.ones()
# torch.zeroes_like(tensor) - copies shape, fills with 0
# torch.eye() fills diagonal ele with 1
# torch.nonzero() displays non zero
# torch.sparse_coo_tensor ( indices - sparse contains data)
# tensor.data