In [6]:
import torch
import numpy as np
import torch.nn as nn
import hiddenlayer as hl

In [4]:
w = torch.randn(6)

x = torch.tensor([10.0, 10.0, 10.0, 10.0, 10.0, 10.0])

b = torch.tensor(3)

In [5]:
y = w*x+b
y

tensor([ 1.8083, 20.6954, -9.9153,  4.6132, -4.0659, -9.1089])

In [8]:
xtrain = np.array([[5,6,7],[3,4,5],[1,2,3]])

In [9]:
xt = torch.tensor(xtrain)
xt

tensor([[5, 6, 7],
        [3, 4, 5],
        [1, 2, 3]])

In [12]:
xtt = torch.from_numpy(xtrain)
xtt

tensor([[5, 6, 7],
        [3, 4, 5],
        [1, 2, 3]])

In [13]:
yt = torch.zeros([10,1])
yt

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])