In [2]:
import torch

print(torch.__version__)

1.4.0


In [5]:
torch.get_default_dtype()

torch.float32

In [39]:
torcharr = torch.Tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
torcharr

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]])

In [8]:
torch.numel(torcharr)

6

In [8]:
torch_initialise = torch.randn(20,10)
torch_initialise

tensor([[-4.0735e-03,  5.4114e-01, -1.3978e-01,  5.1180e-01, -9.2104e-01,
         -1.3800e+00, -1.6184e-03, -1.9551e+00, -3.9501e-01, -6.2244e-01],
        [-1.4646e+00,  1.2396e+00,  1.0022e+00, -5.0958e-01, -2.9364e-01,
          1.3264e+00,  1.9630e-01, -1.1837e+00,  4.3401e-01, -1.2972e+00],
        [ 4.8975e-01, -1.1093e-01,  1.9159e-01, -2.6191e-01,  2.4478e+00,
         -2.9869e-02,  3.6611e-01,  5.8178e-02, -3.7920e-01, -6.1944e-01],
        [-9.0340e-01,  1.2245e+00,  1.3483e+00, -1.3565e-01, -4.6306e-01,
         -1.2162e+00,  1.1467e-01, -1.4403e+00, -1.6657e+00, -1.7864e+00],
        [-1.0751e+00,  7.0873e-01,  1.8994e+00,  2.5911e-01,  2.9803e-01,
          2.3697e+00, -9.7844e-01,  1.2830e+00,  1.1462e+00, -5.2850e-01],
        [-1.2224e-01, -5.9635e-01, -9.3375e-01, -1.1437e+00, -9.2324e-01,
          1.4822e+00,  8.6508e-02,  1.0925e+00,  4.4451e-01,  6.7891e-01],
        [ 1.4958e+00,  1.9707e-01,  4.7231e-01, -1.0198e-01, -2.3976e+00,
          3.4044e-01,  1.7065e+0

In [64]:
torch_int = torch.tensor([5,3]).type(torch.IntTensor)
torch_int

tensor([5, 3], dtype=torch.int32)

In [12]:
torch_fill = torch.full((2,6), fill_value=10)
torch_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [17]:
torch_identity_matrix = torch.eye(4)
torch_identity_matrix

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [18]:
non_zero_positions_of_tensor = torch.nonzero(torch_identity_matrix)
non_zero_positions_of_tensor

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [24]:
#linspace generates numbers in given range with equal interval
x = torch.linspace(start=1, end=10, steps=10)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
#chunk divide the tensor into given number of  parts
tensor_chunk = torch.chunk(torcharr, 2, 1)
tensor_chunk

(tensor([[ 1.,  2.,  3.],
         [ 7.,  8.,  9.],
         [13., 14., 15.]]), tensor([[ 4.,  5.,  6.],
         [10., 11., 12.],
         [16., 17., 18.]]))

In [60]:
y = torch.transpose(torcharr,1,0)
y

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]])

In [61]:
#sort gives sorting of two tensors one is values sorted in each row and other is indices  
torch_sort = torch.sort(torcharr)
torch_sort

torch.return_types.sort(
values=tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]]),
indices=tensor([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]]))

In [73]:
#clamp takes tensor, min, max and performs any value less than 
#min is replace with min value and viceversa
tensorclamp = torch.clamp(torcharr, min=3, max=12)
tensorclamp

tensor([[ 3.,  3.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [12., 12., 12., 12., 12., 12.]])

In [76]:
t = torch.Tensor([[100,3],[40,50]])
torch.argmax(t, dim=1)

tensor([0, 1])

In [10]:
!pip install hiddenlayer